version: 2
jobs:
  build:
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-yarn
          command: npm install && npm run dev-generatesslcerts
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
